Refactor add items
lemonpaul/yandex2spotify pull request #17
Opened 2020-07-21 16:28 UTC by lemonpaul

2020-07-22 09:40 UTC, MarshalX requested changes

2020-07-22 09:40 UTC, MarshalX commented on importer.py
> +from yandex_music.track.track import Track
from yandex_music import Track.....

2020-07-22 09:40 UTC, MarshalX commented on importer.py
> +        if type(item) == Artist:
isinstance для слабых?

2020-07-22 10:16 UTC, lemonpaul commented on importer.py
> +        if type(item) == Artist:
Да

2020-07-22 17:56 UTC, MarshalX requested changes

2020-07-22 17:56 UTC, MarshalX commented on importer.py
> +            type_ = 'track' if isinstance(item, Track) else 'album'
В чем прикол. Уже лучше магии добавь с `__name__` чем такую дичь творить

2020-07-22 17:56 UTC, MarshalX commented on importer.py
> +            type_ = 'track' if isinstance(item, Track) else 'album'
Раз не хочешь в словарь какой-нибудь

2020-07-22 17:56 UTC, MarshalX commented on importer.py
> +        return item_name, found_items[0]['id'] if len(found_items) else None
нафига этот сетовый мусор, выкинь ты исключение с названием трека, если не смогло найти блин, отлови его и добавь в лист свой

2020-07-22 17:57 UTC, MarshalX commented on importer.py
> +        if type(item) == Artist:
А давай ты сам резолвить будешь, а не я за тебя кнопки вечно нажимать

2020-07-22 19:54 UTC, lemonpaul commented on importer.py
> +            type_ = 'track' if isinstance(item, Track) else 'album'
О, а чё, так тоже можно? Окей.

2020-07-22 19:55 UTC, lemonpaul commented on importer.py
> +        return item_name, found_items[0]['id'] if len(found_items) else None
Хорошая мысль...

2020-07-23 00:08 UTC, lemonpaul commented on importer.py
> +        if type(item) == Artist:
О, тут есть кнопка resolve!

2020-07-23 00:09 UTC, lemonpaul commented on importer.py
> +            type_ = 'track' if isinstance(item, Track) else 'album'
А это законно вообще?

2020-07-23 06:33 UTC, MarshalX commented on importer.py
> +        item_name = item.name if type_ == 'artist' else f'{", ".join([artist.name for artist in item.artists])} '\
Я бы здесь оставил проверку принадлежности обьекта к классу, а не вот так. Этот сбор артистов страшный конечно, но я ничего другого предложить не могу. Надо будет перенести в библиотеку... Запиши в issue по шорткатам) 

В остальном ок

2020-07-23 06:53 UTC, lemonpaul commented on importer.py
> +        item_name = item.name if type_ == 'artist' else f'{", ".join([artist.name for artist in item.artists])} '\
А мне кажется, что лучше всё-таки так, без всяких лишних ifов.

2020-07-23 07:41 UTC, MarshalX commented on importer.py
> +        item_name = item.name if type_ == 'artist' else f'{", ".join([artist.name for artist in item.artists])} '\
Рофлишь? У тебя и без этого иф. Я предлагаю нормально сравнивать, а не через строки эти. Условие заменить

2020-07-23 07:58 UTC, lemonpaul commented on importer.py
> +        item_name = item.name if type_ == 'artist' else f'{", ".join([artist.name for artist in item.artists])} '\
А, теперь понял.

2020-07-23 16:53 UTC, MarshalX approved these changes

2020-07-23 16:53 UTC, merged