Spotify read timed out
lemonpaul/yandex2spotify pull request #19
Opened 2020-08-05 09:18 UTC by lemonpaul

2020-08-06 14:51 UTC, MarshalX requested changes

2020-08-06 14:51 UTC, MarshalX commented on importer.py
> +from requests.exceptions import ReadTimeout
прожми автосорт импортов в пучурме

2020-08-06 14:51 UTC, MarshalX commented on importer.py
> +                logger.info(f'Read timed out. (retry={retry})')
странный вывод. (да) 

после точки скобки какие-то

2020-08-06 14:51 UTC, MarshalX commented on importer.py
> +                if retry > MAX_REQUEST_RETRIES:
логических отступов не хочешь сделать с помощью пустых строк?

2020-08-06 14:51 UTC, MarshalX commented on importer.py
> +                handle_spotify_exception(self.spotify_client.playlist_upload_cover_image)(spotify_playlist_id, encode_file_base64_jpeg(filename))
ох не нрав мне такое блин оборачивание. Хоть бери класс спотифай клиента делай, унаследуйся от спотипай клиента и пройдись по методам... декораторов добавь 

заодно похожим образом можешь сделать с клиентом ЯМ увеличив  там таймаут у каждого запроса

2020-08-06 15:14 UTC, lemonpaul commented on importer.py
> +                handle_spotify_exception(self.spotify_client.playlist_upload_cover_image)(spotify_playlist_id, encode_file_base64_jpeg(filename))
Я хотел это сделать в другом pullrequest, давай пока оставим так.

2020-08-06 15:17 UTC, lemonpaul commented on importer.py
> +                logger.info(f'Read timed out. (retry={retry})')
Не знаю, по-моему всё норм. Вот стандартное исключиение, к примеру, выбрасывается вот с таким выводом:
```requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)```

2020-08-06 15:20 UTC, lemonpaul commented on importer.py
> +                if retry > MAX_REQUEST_RETRIES:
Давай добавим, Лишними не будут.

2020-08-06 15:26 UTC, lemonpaul commented on importer.py
> +from requests.exceptions import ReadTimeout
Давай прожмём, чего бы не прожать-то.

2020-08-06 15:46 UTC, lemonpaul commented on importer.py
> +                logger.info(f'Read timed out. (retry={retry})')
Поправил.

2020-08-14 14:33 UTC, MarshalX requested changes

2020-08-14 14:33 UTC, MarshalX commented on importer.py
> +                logger.info(f'Read timed out (retry={retry}).')
сложно понять, что номер попытки. Больше выглядит как дебаг инфа чему равна переменная. Почему явно не скзать, аля "попытка отправки запроса номер 4"

2020-08-29 14:07 UTC, lemonpaul commented on importer.py
> +                logger.info(f'Read timed out (retry={retry}).')
Оставился на варианте с "Retrying #1..."

2020-08-31 21:29 UTC, MarshalX approved these changes

2020-09-02 17:16 UTC, merged