Ability to ignore likes, playlists, albums and artists
lemonpaul/yandex2spotify pull request #9
Opened 2020-07-17 20:38 UTC by glebliutsko

2020-07-17 21:38 UTC, MarshalX requested changes
Чет стремно, подумай еще. Может уже стоит какой-то класс сделать, где будет словарь с вариантами импорта. Ключ - импорт (лайов, плейлистов и т.д.), значение - булька вкл/выкл. И там где-нить в import_all проход по ключам, у который значение True.

2020-07-18 10:41 UTC, lemonpaul requested changes

2020-07-18 10:41 UTC, lemonpaul commented on main.py
>      def __init__(self, spotify_client, yandex_client, ignore_like, ignore_playlists, ignore_albums, ignore_artists):
Лучше передавать ignore одним аргументом.

2020-07-18 11:39 UTC, lemonpaul requested changes

2020-07-18 11:39 UTC, lemonpaul commented on main.py
> +    parser.add_argument('--ignore', nargs='+', help='Don\'t import some stuff',
Добавь сокращение -i для этого аргумента, и в help вместо термина stuff я бы использовал items.

2020-07-18 14:19 UTC, lemonpaul requested changes

2020-07-18 14:19 UTC, lemonpaul commented on main.py
> +from typing import NamedTuple, Callable
Лишний import

2020-07-18 14:21 UTC, lemonpaul approved these changes

2020-07-18 19:31 UTC, MarshalX commented on main.py
> +    parser.add_argument('-i', '--ignore', nargs='+', help='Don\'t import some items',
Вопрос. А можно ли передать несколько таких параметров для игнора двух и более импортом? Если нет, то надо тюнить

2020-07-18 19:31 UTC, MarshalX commented on main.py
> +    parser.add_argument('-i', '--ignore', nargs='+', help='Don\'t import some items',
Как работает Mary's?

2020-07-18 19:35 UTC, MarshalX requested changes
Забыл обновить ридми с примерами использования. А так мне нравится

2020-07-19 06:17 UTC, merged